import { text, timestamp, integer, boolean, index, uniqueIndex, pgPolicy } from 'drizzle-orm/pg-core';
import { sql } from 'drizzle-orm';
import { scholioSchema } from '../scholio-schema';
import { project } from './projects.schema';

export const documentTypeEnum = scholioSchema.enum('document_type', [
	'paper',
	'notes',
	'outline',
	'bibliography',
	'supplementary',
	'book',
	'chapter',
	'reading_note'
]);

export const document = scholioSchema.table(
	'document',
	{
		id: text('id').primaryKey(),
		projectId: text('project_id')
			.notNull()
			.references(() => project.id, { onDelete: 'cascade' }),
		title: text('title').notNull(),
		type: documentTypeEnum('type').notNull().default('paper'),
		// FK no forzada para evitar dependencia circular con documentVersion
		currentVersionId: text('current_version_id'),
		// Contenido en progreso (auto-save). null = sin cambios desde el último commit
		draftContent: text('draft_content'),
		// Owner can make a document publicly readable (for AI context sharing)
		isPublic: boolean('is_public').notNull().default(false),
		// Private note: only the creator can see and edit it (not even project owner)
		isPrivate: boolean('is_private').notNull().default(false),
		// User who created this document. Required for isPrivate RLS enforcement.
		ownerUserId: text('owner_user_id'),
		// Marks this document as a reusable template within the project
		isTemplate: boolean('is_template').notNull().default(false),
		// Set when document content was generated by AI (draft generation, summary, etc.)
		generatedByAi: boolean('generated_by_ai').notNull().default(false),
		// 1 writer / N readers: user currently allowed to edit (besides the project owner).
		// NULL  → only the project owner can write.
		// SET   → only this user can write; owner loses write access until they reclaim it.
		writerUserId: text('writer_user_id'),
		// Imported/external content that should not be accidentally edited
		isReadonly: boolean('is_readonly').notNull().default(false),
		// Pre-rendered HTML for readonly imported documents (avoids re-rendering on every request)
		renderedHtml: text('rendered_html'),
		// Reference this document was imported from (EPUB chapter, URL import, etc.)
		sourceReferenceId: text('source_reference_id'),
		// BCP-47 language code for spell checking. null = auto-detect
		spellLanguage: text('spell_language'),
		createdAt: timestamp('created_at').notNull().defaultNow(),
		updatedAt: timestamp('updated_at').notNull().defaultNow()
	},
	(t) => [
		index('document_project_idx').on(t.projectId),
		uniqueIndex('document_project_title_idx').on(t.projectId, t.title),

		// SELECT: private → only creator; shared → owner or any collaborator
		pgPolicy('document_select', {
			for: 'select',
			using: sql`
				(${t.isPrivate} = true AND ${t.ownerUserId} = current_setting('app.current_user_id', true))
				OR
				(${t.isPrivate} = false AND EXISTS (
					SELECT 1 FROM scholio.project
					WHERE project.id = ${t.projectId}
					AND (
						project.owner_id = current_setting('app.current_user_id', true)
						OR EXISTS (
							SELECT 1 FROM scholio.project_collaborator
							WHERE project_collaborator.project_id = project.id
							AND project_collaborator.user_id = current_setting('app.current_user_id', true)
						)
					)
				))
			`
		}),
		// INSERT: private → creator only (ownerUserId must match); shared → owner or collaborator
		pgPolicy('document_insert', {
			for: 'insert',
			withCheck: sql`
				(${t.isPrivate} = true AND ${t.ownerUserId} = current_setting('app.current_user_id', true)
					AND EXISTS (
						SELECT 1 FROM scholio.project
						WHERE project.id = ${t.projectId}
						AND (
							project.owner_id = current_setting('app.current_user_id', true)
							OR EXISTS (
								SELECT 1 FROM scholio.project_collaborator
								WHERE project_collaborator.project_id = project.id
								AND project_collaborator.user_id = current_setting('app.current_user_id', true)
							)
						)
					)
				)
				OR
				(${t.isPrivate} = false AND EXISTS (
					SELECT 1 FROM scholio.project
					WHERE project.id = ${t.projectId}
					AND (
						project.owner_id = current_setting('app.current_user_id', true)
						OR EXISTS (
							SELECT 1 FROM scholio.project_collaborator
							WHERE project_collaborator.project_id = project.id
							AND project_collaborator.user_id = current_setting('app.current_user_id', true)
						)
					)
				))
			`
		}),
		// UPDATE: private → only creator; shared → 1-writer invariant
		pgPolicy('document_update', {
			for: 'update',
			using: sql`
				(${t.isPrivate} = true AND ${t.ownerUserId} = current_setting('app.current_user_id', true))
				OR
				(${t.isPrivate} = false AND EXISTS (
					SELECT 1 FROM scholio.project
					WHERE project.id = ${t.projectId}
					AND (
						(${t.writerUserId} IS NULL AND project.owner_id = current_setting('app.current_user_id', true))
						OR ${t.writerUserId} = current_setting('app.current_user_id', true)
					)
				))
			`
		}),
		// DELETE: private → creator; shared → project owner
		pgPolicy('document_delete', {
			for: 'delete',
			using: sql`
				(${t.isPrivate} = true AND ${t.ownerUserId} = current_setting('app.current_user_id', true))
				OR
				(${t.isPrivate} = false AND EXISTS (
					SELECT 1 FROM scholio.project
					WHERE project.id = ${t.projectId}
					AND project.owner_id = current_setting('app.current_user_id', true)
				))
			`
		}),
		// Public documents are readable by anyone (SELECT only)
		pgPolicy('document_public_read', {
			for: 'select',
			using: sql`${t.isPublic} = true`
		})
	]
).enableRLS();

export const documentVersion = scholioSchema.table(
	'document_version',
	{
		id: text('id').primaryKey(),
		documentId: text('document_id')
			.notNull()
			.references(() => document.id, { onDelete: 'cascade' }),
		content: text('content').notNull().default(''),
		versionNumber: integer('version_number').notNull().default(1),
		changeDescription: text('change_description'),
		// AI-generated summary for use by the project chat agent
		aiSummary: text('ai_summary'),
		createdBy: text('created_by').notNull(),
		createdAt: timestamp('created_at').notNull().defaultNow()
	},
	(t) => [
		index('document_version_document_idx').on(t.documentId, t.versionNumber),

		// Hereda acceso via document (la policy de document ya filtra por proyecto)
		pgPolicy('document_version_access', {
			for: 'all',
			using: sql`
				EXISTS (
					SELECT 1 FROM scholio.document
					WHERE document.id = ${t.documentId}
				)
			`
		})
	]
).enableRLS();

export const documentVersionShare = scholioSchema.table(
	'document_version_share',
	{
		id: text('id').primaryKey(),
		versionId: text('version_id')
			.notNull()
			.references(() => documentVersion.id, { onDelete: 'cascade' }),
		documentId: text('document_id')
			.notNull()
			.references(() => document.id, { onDelete: 'cascade' }),
		token: text('token').notNull().unique(),
		createdBy: text('created_by').notNull(),
		expiresAt: timestamp('expires_at').notNull(),
		revokedAt: timestamp('revoked_at'),
		createdAt: timestamp('created_at').notNull().defaultNow()
	},
	(t) => [
		index('dvshare_version_idx').on(t.versionId),
		index('dvshare_document_idx').on(t.documentId),
		uniqueIndex('dvshare_token_idx').on(t.token),

		// Public read: token-based access — no RLS user required
		pgPolicy('dvshare_public_read', {
			for: 'select',
			using: sql`true`
		}),
		// Write: only document owner
		pgPolicy('dvshare_owner_write', {
			for: 'all',
			using: sql`
				EXISTS (
					SELECT 1 FROM scholio.document
					WHERE document.id = ${t.documentId}
					AND document.owner_user_id = current_setting('app.current_user_id', true)
				)
			`
		})
	]
).enableRLS();
