name: Build and Push Embed Service to GHCR

on:
  workflow_dispatch:
  push:
    branches:
      - staging
    paths:
      - "embed-service/**"

env:
  REGISTRY: ghcr.io
  # Forzamos el nombre para que sea un paquete independiente en tu perfil
  IMAGE_NAME: ${{ github.repository_owner }}/scholio-embed

jobs:
  build-and-push-typst:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./embed-service
          file: ./embed-service/Dockerfile # <--- SU DOCKERFILE
          push: true
          platforms: linux/amd64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
